apiVersion: v1
kind: ReplicationController
metadata:
  name: echo-server
spec:
  replicas: 1
  selector:
    component: echo-server
  template:
    metadata:
      labels:
        component: echo-server
    spec:
      containers:
      - name: echo-server
        image: craigwillis/echoserver
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: echo-server
  name: echo-server
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: echo-server
