apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    component: webserver
  template:
    metadata:
      labels:
        component: webserver
    spec:
      containers:
      - name: webserver
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    component: webserver
